# This is a basic workflow to help you get started with Actions

name: Terraform Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  terraform:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Set environment variables (optional, specify keys later in GitHub Secrets)
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      # Runs `terraform init`
      - name: Terraform Init
        run: terraform init

      # Runs `terraform validate`
      - name: Terraform Validate
        run: terraform validate

      # Runs `terraform plan` and saves the output to a file
      - name: Terraform Plan
        run: terraform plan -out=tfplan
